[2023-12-05 00:37:21,659][flwr][INFO] - Starting Flower simulation, config: ServerConfig(num_rounds=10, round_timeout=None)
[2023-12-05 00:37:25,435][flwr][INFO] - Flower VCE: Ray initialized with resources: {'CPU': 40.0, 'accelerator_type:P100': 1.0, 'object_store_memory': 59530967040.0, 'GPU': 1.0, 'memory': 128905589760.0, 'node:128.105.144.67': 1.0}
[2023-12-05 00:37:25,436][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.dev/docs/framework/how-to-run-simulations.html
[2023-12-05 00:37:25,436][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 4, 'num_gpus': 0.2}
[2023-12-05 00:37:25,473][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 5 actors
[2023-12-05 00:37:25,473][flwr][INFO] - Initializing global parameters
[2023-12-05 00:37:25,473][flwr][INFO] - Requesting initial parameters from one random client
[2023-12-05 00:37:33,821][flwr][ERROR] - Traceback (most recent call last):
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters
    return maybe_call_get_parameters(
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters
    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if 'bn' not in name] # from tutorial
AttributeError: 'FlowerClient' object has no attribute 'model'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 7 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters\n    return maybe_call_get_parameters(\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters\n    return client.get_parameters(get_parameters_ins)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters\n    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore\n  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters\n    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if \'bn\' not in name] # from tutorial\nAttributeError: \'FlowerClient\' object has no attribute \'model\'\n',)

[2023-12-05 00:37:33,822][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters
    return maybe_call_get_parameters(
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters
    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if 'bn' not in name] # from tutorial
AttributeError: 'FlowerClient' object has no attribute 'model'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 7 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters\n    return maybe_call_get_parameters(\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters\n    return client.get_parameters(get_parameters_ins)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters\n    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore\n  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters\n    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if \'bn\' not in name] # from tutorial\nAttributeError: \'FlowerClient\' object has no attribute \'model\'\n',)
[2023-12-05 00:37:33,822][flwr][ERROR] - [36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters
    return maybe_call_get_parameters(
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters
    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if 'bn' not in name] # from tutorial
AttributeError: 'FlowerClient' object has no attribute 'model'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 7 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters\n    return maybe_call_get_parameters(\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters\n    return client.get_parameters(get_parameters_ins)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters\n    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore\n  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters\n    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if \'bn\' not in name] # from tutorial\nAttributeError: \'FlowerClient\' object has no attribute \'model\'\n',)
[2023-12-05 00:37:33,825][flwr][ERROR] - Traceback (most recent call last):
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/app.py", line 308, in start_simulation
    hist = run_fl(
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/server/app.py", line 225, in run_fl
    hist = server.fit(num_rounds=config.num_rounds, timeout=config.round_timeout)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/server/server.py", line 90, in fit
    self.parameters = self._get_initial_parameters(timeout=timeout)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/server/server.py", line 279, in _get_initial_parameters
    get_parameters_res = random_client.get_parameters(ins=ins, timeout=timeout)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 180, in get_parameters
    res = self._submit_job(get_parameters, timeout)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 147, in _submit_job
    raise ex
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 138, in _submit_job
    res = self.actor_pool.get_client_result(self.cid, timeout)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 414, in get_client_result
    return self._fetch_future_result(cid)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 300, in _fetch_future_result
    res_cid, res = ray.get(future)  # type: (str, ClientRes)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ClientException): [36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters
    return maybe_call_get_parameters(
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters
    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if 'bn' not in name] # from tutorial
AttributeError: 'FlowerClient' object has no attribute 'model'

The above exception was the direct cause of the following exception:

[36mray::DefaultActor.run()[39m (pid=564907, ip=128.105.144.67, repr=<flwr.simulation.ray_transport.ray_actor.DefaultActor object at 0x7ff5302a3250>)
  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 84, in run
    raise ClientException(str(message)) from ex
flwr.simulation.ray_transport.ray_actor.ClientException: 
>>>>>>>A ClientException occurred.('\n\tSomething went wrong when running your client workload.\n\tClient 7 crashed when the DefaultActor was running its workload.\n\tException triggered on the client side: Traceback (most recent call last):\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_actor.py", line 72, in run\n    job_results = job_fn(client)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/simulation/ray_transport/ray_client_proxy.py", line 175, in get_parameters\n    return maybe_call_get_parameters(\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/client.py", line 203, in maybe_call_get_parameters\n    return client.get_parameters(get_parameters_ins)\n  File "/users/wang2451/miniconda3/envs/flower/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 214, in _get_parameters\n    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore\n  File "/users/wang2451/Fed_with_flower/client.py", line 40, in get_parameters\n    return [val.cpu().numpy() for name, val in self.model.state_dict().items() if \'bn\' not in name] # from tutorial\nAttributeError: \'FlowerClient\' object has no attribute \'model\'\n',)

[2023-12-05 00:37:33,826][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons.The most common are: 
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 4, 'num_gpus': 0.2} is not enough for your workload). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 4, 'num_gpus': 0.2}.
